### ISSUE TITLE
Support tsv files produced by older snowplow versions

### ISSUE THREAD

**Issue by bamos** [bamos/snowglobe#11]
\cc @alexanderdean
- Since upgrading snowplow, I've added fields to the event object, so Cassava's (reasonably) not able to parse the old event format.
- This might be an easy fix and useful for integrating future snowplow updates since snowplow only appends entries to their events object.
- Might also be a good opportunity to support supporting data in multiple events files so that they won't grow very large after a few years, for example.

```
snowglobe(master)$ ./dist/build/snowglobe-analysis/snowglobe-analysis --events ./data/events-pre-2015-05-20.tsv DayReport
parse error (Failed reading: conversion error: cannot unpack array of length 108 into a 108-tuple.
```

**Comment by alexanderdean** [comment]
Hey @bamos ! All makes sense. A couple of notes from our side:
- We are getting belatedly getting better (!) at versioning/documenting our enriched event model: https://github.com/snowplow/snowplow/wiki/Canonical-event-model
- For now updates are append-only. However at some stage soon we will be aggressively removing fields as they migrate into dedicated JSONs with proper JSON Schemas
- Some time after that, we will be wholly replacing the enriched event TSV with an Avro format

Hope that helps...
