### ISSUE TITLE
Find subtle bug from geo enrichments not being in events

### ISSUE THREAD

**Issue by bamos** [bamos/snowglobe#4]

**Comment by alexanderdean** [comment]
Could be related to https://github.com/snowplow/snowplow/issues/1664 or https://github.com/snowplow/snowplow/issues/1645

Here's a config that's known to work:

``` json
{
    "schema": "iglu:com.snowplowanalytics.snowplow/ip_lookups/jsonschema/1-0-0",

    "data": {

        "name": "ip_lookups",
        "vendor": "com.snowplowanalytics.snowplow",
        "enabled": true,
        "parameters": {
            "geo": {
                "database": "GeoLiteCity.dat",
                "uri": "http://snowplow-hosted-assets.s3.amazonaws.com/third-party/maxmind"
            }
        }
    }
}
```

**Comment by bamos** [comment]
Thanks Alex! I'm using v0.2.1 of the kinesis enricher, and it looks like it's been bumped from 0.2.1 to 0.5.0 between December 2014 and now, so updating this and the associated events format is probably the solution to this issue.

**Comment by alexanderdean** [comment]
Yep, 0.2.1 is pretty out of date now!

**Comment by bamos** [comment]
@alexanderdean - geo enrichments in the latest Snowplow build are working well!

**Comment by alexanderdean** [comment]
Ace!
